name: GitHub 3D Contrib

on:
  schedule:
    - cron: "0 18 * * *"   # runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: realshivamarora

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}